# https://circleci.com/docs/2.0/language-python/

version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    context: techworks
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: "True"
          AWS_RESOURCE_NAME_PREFIX: circleci-py-demo
          DATABASE_URL: postgresql://root:password@localhost/circle_test?sslmode=disable
          #DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - '.venv'
            - '/usr/local/bin'
            - '/usr/local/lib/python3.6/site-packages'
      - run:
          command: |
            pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - run:
          name: Install AWS CLI
          command: |
            # -eo pipefail is default
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              pip install awscli
              echo aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID} --profile default
              echo aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY} --profile default
              echo aws configure set region ${AWS_DEFAULT_REGION} --profile default
              cat ~/.aws/config
              cat ~/.aws/credentials
              echo aws s3 ls
            fi 

            
       